### ISSUE TITLE
Xcode 10.2.1

### ISSUE THREAD

**Issue by GrahamCampbell** [travis-ci/packer-templates-mac#11]
Will Xcode 10.2.1 be supported soon? The current version on travis is 10.2.0.

**Comment by mjm** [comment]
We should have it up today. It will replace the current `xcode10.2` image.

**Comment by mjm** [comment]
👍 Should be out now. Builds for `osx_image: xcode10.2` will now run Xcode 10.2.1. The info on the docs will be updated shortly.

**Comment by GrahamCampbell** [comment]
🍻
